- .github/workflows/codeql.yml
Adds CodeQL action, which is Security Scanning for Open Source projects, provided by GitHub.
**Ready**
> AC-967 Added CodeQL Action

- documentation/accessibility-statement.md
Add accessibility statement markdow file for future use.
**Ready**
> Add accessibility markdown file

- documentation/accessibility-statement.md
- src/views/AccessibilityStatement.vue
> minor accessibility changes

- cypress/data/payloads-dashboard/payloadTree.ts
- cypress/data/system-dashboard/issues.ts
- cypress/e2e/systemDashboard_test.cy.ts
- cypress/fixtures/mockIndex.ts
- cypress/fixtures/payload-dashboard/payloadTable.json
- cypress/fixtures/payload-dashboard/payloadTaskRedirect.json
- cypress/fixtures/system-dashboard/adminDashboardIssues.json
- cypress/pages/systemDashboard.ts
- src/__mocks__/issues.ts
- src/__mocks__/payloads.ts
- src/components/AdminHealthDashboard/IssuesTable.vue
- src/components/AdminPayloadDashboard/ExecutionTree.vue
- src/components/AdminPayloadDashboard/PayloadsTable.vue
- src/components/Shared/JSONViewerDialog.vue
- src/models/Admin/IIssue.ts
- src/models/Admin/IPayload.ts
Fixes AC-640 .
Updated Issues table on admin system dashboard to redirect the user to Payloads table when View Logs or View Rejection is clicked.
**Hold**
> AC-640 - Navigate to payload tree

- src/api/Admin/payloads/PayloadService.ts
- src/components/AdminPayloadDashboard/ModelDetailsSection.vue
Signed-off-by: Sam Rooke <sam.rooke@answerdigital.com>
Fixes # .
> AC-761: fix issue with output download

- documentation/accessibility-statement.md
- src/views/AccessibilityStatement.vue
AC-990 Added missing contact details
**Ready**
> AC-990 Added contact details

- .github/workflows/codeql.yml
- .github/workflows/develop.yml
Fixes - Updating a ref
**Ready**
> Updated "master" ref to "main"

- cypress/fixtures/clinical-review/allTasks.json
- cypress/fixtures/clinical-review/paginationPage10.json
- cypress/fixtures/clinical-review/paginationPage2.json
- cypress/fixtures/clinical-review/paginationPage9.json
- cypress/fixtures/clinical-review/searchApplicationName.json
- cypress/fixtures/clinical-review/searchPatientId.json
- cypress/fixtures/clinical-review/searchPatientName.json
- cypress/pages/clinicalReview.ts
- src/__mocks__/clinical-review.ts
- src/components/clinical-review/tasks/task-item.cy.ts
- src/components/clinical-review/tasks/task-item.vue
- src/models/ClinicalReview/ClinicalReviewTask.ts
Fixes AC-1000 : Fix Name/version on CR task details
**Work in progress**
> AC-1000 : Fix Name/version on CR task details

- src/components/AdminPayloadDashboard/ExecutionTree.vue
- src/components/AdminPayloadDashboard/PayloadsTable.vue
- src/views/AdminPayloadDashboard.vue
Updated the styling of the Payloads table on Payloads Dashboard to remove the fixed width and match the styling with Issues table on System Dashboard.
**Ready**
> Update the styling of payloads table

- src/__mocks__/payloads.ts
- src/components/AdminPayloadDashboard/ExecutionTree.vue
- src/utils/workflow-instance-mapper.ts
Fixes #AC-1006.
Added an empty workflow node which represents no workflow being triggered
**Ready**
> AC-1006 : Added empty "No Workflow Triggered" node

- cypress/e2e/clinicalReview_test.cy.ts
- cypress/pages/clinicalReview.ts
- src/components/clinical-review/tasks/task-list.vue
> AC-1064 - When using pagination on CR, focus is not on top CR task

- cypress/fixtures/clinical-review/allTasks.json
- cypress/fixtures/clinical-review/paginationPage10.json
- cypress/fixtures/clinical-review/paginationPage2.json
- cypress/fixtures/clinical-review/paginationPage9.json
- cypress/fixtures/clinical-review/searchApplicationName.json
- cypress/fixtures/clinical-review/searchPatientId.json
- cypress/fixtures/clinical-review/searchPatientName.json
- cypress/pages/clinicalReview.ts
- src/__mocks__/clinical-review.ts
- src/components/clinical-review/patient-header.cy.ts
- src/components/clinical-review/patient-header.vue
- src/components/clinical-review/tasks/task-item.cy.ts
- src/components/clinical-review/tasks/task-item.vue
- src/components/clinical-review/tasks/task-list.cy.ts
- src/models/ClinicalReview/ClinicalReviewTask.ts
Signed-off-by: Lillie Dae <lillie.dae@answerdigital.com>
Gender != Sex
MonAi extracts sex, not the gender.
**Ready**
> Gender to sex

- src/utils/axios-helpers.ts
Fixes AC-1076 .
Added a toast message for unauthorised requests.
> AC-1076 - Add a toast message for unauthorised requests

- cypress/pages/userManagement.ts
- src/components/AdminPayloadDashboard/PayloadsTable.vue
- src/components/admin-destination-configuration/DicomExportConfiguration.vue
- src/components/user-management/UserRolesTabItem.vue
- src/components/user-management/UserTabItem.vue
- src/views/Workflows.vue
Fixes #AC-1003 : Show skeleton load for Workloads and Payloads .
**Ready**
> AC-1003 : Workflows/Payloads - Show skeleton load

- cypress/e2e/systemDashboard_test.cy.ts
- cypress/pages/systemDashboard.ts
> remove hardcoded 400

- src/components/AdminHealthDashboard/IssuesTable.vue
Fixes AC-1086.
- added column width for patient ID column
- set items per page options
> Update issues table

- src/components/clinical-review/accept-reject-dialog.vue
Fixes AC-1093.
Update the validation trigger for the task rejection reason.
**Ready**
> Update validation trigger

- src/components/AdminHealthDashboard/IssuesTable.vue
https://user-images.githubusercontent.com/10155704/208660064-ecae22f1-e6fd-4de5-875b-a76eb97ee4b8.mp4
Fixes AC-1086.
**Ready**
> Set col widths for issues table

- cypress/fixtures/clinical-review/noTasks.json
- cypress/pages/clinicalReview.ts
- src/__mocks__/clinical-review.ts
- src/components/clinical-review/tasks/task-list.vue
Fixes #1077 - Fixes of searching/pagination for Clinical Reviews
**Ready**
> AC-1077 : Clinical Reviews pagination/search fixes

- src/components/Shared/JSONViewer.vue
- src/components/user-management/UserRolesTabItem.vue
- src/components/user-management/UserTabItem.vue
- src/views/WorkflowEditor.vue
- src/views/Workflows.vue
This PR fixes some of the accessibility issues reported in AC-1005.
**Ready**
> Fix accessibility issue

- src/__mocks__/issues.ts
- src/components/AdminHealthDashboard/IssuesTable.vue
- src/models/Admin/IIssue.ts
Signed-off-by: Jack Schofield <jack.schofield@answerdigital.com>
Fixes # .
> fix partial fail on frontend

- .github/workflows/license-scanning.yml
- .licenserc.yaml
- .nsprc
- cypress/pages/userManagement.ts
- public/env-config.js
- src/components/clinical-review/metadata/metadata-list.vue
- src/components/clinical-review/viewer/dicom-canvas.vue
- src/components/user-management/UserRolesTabItem.vue
- src/components/user-management/UserTabItem.vue
Fixes some issues with the metadata list.
**Ready**
> Metadata issue fix

- src/components/clinical-review/tasks/task-list.vue
Signed-off-by: Jack Schofield <jack.schofield@answerdigital.com>
Fixes # .
**Ready**
> change last page clinical review

- documentation/accessibility-statement.md
- src/views/AccessibilityStatement.vue
> Update statement to reflect accessibility we can't change

- src/__mocks__/clinical-review.ts
- src/components/clinical-review/series/series-dicom-thumbnail.vue
- src/components/clinical-review/series/series-item.vue
> AC-1174 - Only configure the DICOM thumbnail if series is present

- documentation/accessibility-statement.md
- src/views/AccessibilityStatement.vue
Update accessibility statement.
**Ready**
> AC-1114 Update accessibility statement

- documentation/accessibility-statement.md
- src/views/AccessibilityStatement.vue
> Minor accessibility update
